### ISSUE TITLE
Add filter to remove closed tournaments

### ISSUE THREAD

**Issue by salgozino** [prodeapp/prodeapp#43]
In the home page all the tournaments are listed, but a button should be there to be possible hide the old tournaments that were already closed.

**Comment by salgozino** [comment]
I've decided to use the "hasPendingAnswers" field, because filtering by this condition will show all the markets except those in claiming period or finished. Using closingTime will filter also those markets waiting for answers.
Maybe we have to re-think this to show also the markets in period of Claiming rewards :thinking: . Or split the view to show in the home page only those markets that are available to bet, and in another view, show ongoing tournaments but not accepting bets. :thinking:

**Comment by rodsouto** [comment]
I'd go with three mutually exclusive filters:

1) Active (markets accepting bets)
2) Pending (markets waiting answers)
3) Closed (markets ready to claim rewards / with rewards already claimed)
