### ISSUE TITLE
New tournament should have an Name and Symbol 

### ISSUE THREAD

**Issue by salgozino** [prodeapp/prodeapp#8]

**Comment by rodsouto** [comment]
`name` added in f0b2439d433e8d004fd3704f43bac8fa869a1151

**Comment by salgozino** [comment]
name, symbol and uri already setted in subgraph

**Comment by rodsouto** [comment]
what should we use for symbol and uri @fnanni-0 ?

https://github.com/prodeapp/prodeapp/blob/4edb3940314c047033932e9d2dd4204f706db95f/packages/react-app/src/components/TournamentCreate/TournamentForm.tsx#L96-L97
